### ISSUE TITLE
Sponsored Brands - missing sb2 campaigns in amazon ads api

### ISSUE THREAD

**Issue by naveenpatnana** [amzn/ads-advanced-tools-docs#113]
**Describe the bug**
We are calling this API - **https://advertising-api-eu.amazon.com/sb/campaigns** to get all the metrics against each Ad group, campaign data from Amazon Ads API. However, there are sb2 campaigns that are shown in the front-end report which are not available in the data sent via API.

**Comment by elizafarley** [comment]
Hi @naveenpatnana, to get data for both V2 and V3 SB campaigns, you need to use `"creativeType": "all"` as part of your report request.

For example, a request for a campaigns report should look like:

```bash
curl --request POST 'https://advertising-api-eu.amazon.com/v2/hsa/campaigns/report' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer xxxxxx' \
--header 'Amazon-Advertising-API-ClientId: xxxxxx' \
--header 'Amazon-Advertising-API-Scope: xxxxxx' \
--data-raw '{
"reportDate": "20211102",
"metrics": "impressions,clicks,cost,attributedConversions14d,attributedSales14d",
"creativeType": "all"
}'
```
Let me know if that helps!

**Comment by naveenpatnana** [comment]
@elizafarley Thanks for your comment. We are able to get SB2 campaign using creativeType: all but how do we differentiate Sponsored video campaigns from this list? Is there any dimension that we could add that would signify the campaign type?

Earlier we used to fetch data in 2 stream one with creativeType: 'video' and other without passing any parameter for "creativeType" (which our understanding is that it would fetch all campaigns which are not video) but SB2 campaigns were neither  in 'Video' campaigns nor in the stream without creativeType.


Appreciate your time.

**Comment by elizafarley** [comment]
Glad that you are now able to get data for SB v4 campaigns. 

In SB version 4, one campaign can contain both image and video creatives, so there is no longer a distinction between video and non-video campaigns.

**Comment by GregThoen** [comment]
Hi @elizafarley 
I had not seen that SB campaigns can now contain both image and video creatives in the same campaign so that there's no longer a distinction between video and non video SB.  With that being the case, I'm not sure how to make sense of https://advertising.amazon.com/API/docs/en-us/reference/concepts/limits, particularly the "Bid constraints by marketplace" table.  We set bids for our clients' keywords, including for SB campaigns. Until now, we've had to differentiate in our system between video and non-video SB campaigns because there are different min and max bids allowed for video vs. non-video, as you can see in that table.  With this change that you're mentioning (which unfortunately I don't see mentioned in the migration guide at https://advertising.amazon.com/API/docs/en-us/reference/migration-guides/sb-v3-v4 or elsewhere in the documentation), how do we know what the min and max allowable bids are for a given SB campaign?
Thanks,
Greg

**Comment by elizafarley** [comment]
Hi @GregThoen, the bid limits are still in place for video vs. non-video ads. 

Bid limits are still applied at the ad-group level based on the ad format (image or video) associated with the ad group. If the ad group contains video ads, you need to use the video bid limits. If the ad group contains non-video ads, you use the non-video bid limits. Ad groups can only contain one type of ad format, which can be found by listing the ads associated with the ad group and checking the type field. 

Hopefully that helps clarify!

**Comment by GregThoen** [comment]
Ok - thanks for the clarification.
