### ISSUE TITLE
Issue Report: /en-us/dsp-reports-beta-3p Content-Type cause HTTP 415

### ISSUE THREAD

**Issue by bartektrybala** [amzn/ads-advanced-tools-docs#215]
**Describe the bug**
POST request on /accounts/{accountId}/dsp/reports
Your current Content-Type suggestion ('application/vnd.dspcreatereports.v3+json') cause `HTTP 415 Unsupported Media Type` error. It should be "application/json". Also the success response returns HTTP 202 not the 200.

**URL of the content**
https://advertising.amazon.com/API/docs/en-us/dsp-reports-beta-3p#tag/Reports/operation/createReportV3

**Description of what the documentation currently says**
 - Content type 'application/vnd.dspcreatereports.v3+json'
 - Success response status code 200

**Description of what the documentation should say**
 - Content type 'application/json'
 - Success response status code 202

**Comment by glmcmull** [comment]
Thanks for submitting this report!

I've let the engineering team know. However, a new ADSP report API is being released this quarter. The current report API is on a deprecation path and will be sunset later this year. We will be asking all customers to migrate to the new API, and we likely won't have capacity to make updates to the legacy report API. Since this issue was also reported in JIRA, I'll close this ticket for now and we'll let you know in JIRA if anything changes.
