### ISSUE TITLE
Sample curl when create Sponsored Display campaign is not correct

### ISSUE THREAD

**Issue by martinsangdo** [amzn/ads-advanced-tools-docs#24]
Hi,
I am following exactly steps to create PD campaign via this link:

https://advertising.amazon.com/API/docs/en-us/sponsored-display/tutorials/how-to-build-audt-campaigns
Payload:
`[
    {
        "name": "martin postman Product Targeting Campaign",
        "tactic": "T00020",
        "startDate": "20221009",
        "endDate": "20201231",
        "state": "enabled",
        "budget": 1.0,
        "budgetType": "daily"
    }
]`
However the error comes:
[
    {
        "code": "INVALID_ARGUMENT",
        "description": "Tactic must be one of [remarketing]"
    }
]

Both "tactic": "T00020" or "T00030" giving same error.
I am testing in Test account.

**Comment by jerirose** [comment]
Hi @martinsangdo , because the `endDate` in the request body above is in the past, the request would be expected to produce a different error:

```json
[{
    "code": "INVALID_ARGUMENT",
    "description": "End date cannot be before start date"
}]
```

Your request should succeed if you retry using a `startDate` and `endDate` that are both in the future. 

If you continue to receive the `"description": "Tactic must be one of [remarketing]"` error message, we would encourage you to create a Jira ticket through the [Amazon Ads API Service Desk](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2).

**Comment by jerirose** [comment]
@martinsangdo Please feel free to re-open this ticket if you are still unable to make this call.
