### ISSUE TITLE
#415 errors 

### ISSUE THREAD

**Issue by 24ChangQing** [amzn/ads-advanced-tools-docs#25]
When I try to use negative keywords api, I am getting a 415 error.
But there is no workaround for this error in the documentation.

the link is : /v2/sp/campaignNegativeKeywords

My json data is:
[
  {
    "campaign_id": 227127083389297,
    "state": "enabled",
    "keywordText": "helloworld",
    "matchType": "negativeExact"
  }
]

**Comment by elizafarley** [comment]
Hi @24ChangQing, I believe this issue could be due to use the of the `Content-Type` header. Make sure it is set to `application/json` as seem in the curl sample here:

```
curl --location --request POST 'https://advertising-api.amazon.com/v2/sp/campaignNegativeKeywords' \
--header 'Amazon-Advertising-API-ClientId: amzn1.application-oa2-client.xxxxxxxxxxxxxxx' \
--header 'Authorization: Bearer Atza|xxxxxxxxxxxxxx' \
--header 'Amazon-Advertising-API-Scope: xxxxxxxxxxxxx' \
--header 'Content-Type: application/json' \
--data-raw '[
  {
    "campaignId": 26256301417055,
    "state": "enabled",
    "keywordText": "helloworld",
    "matchType": "negativeExact"
  }
]'
```

We are also working on enhancements to the documentation for Sponsored Products to provide more code samples, so look out for that soon!

**Comment by elizafarley** [comment]
@24ChangQing Let me know if you are still not able to make a successful call, otherwise I will close the issue for now.
