### ISSUE TITLE
`name` and `advertiserId` missing in creative

### ISSUE THREAD

**Issue by davidmoss** [amzn/ads-advanced-tools-docs#94]
**Describe the bug**
According to the docs and APi schema a `DspImageCreativeV1` should always have both `name` and `advertiserId` but these are sometimes missing in `/dsp​/creatives​/image`. When you retrieve the listing of creatives both fields are always present though.

**URL of the content**
https://advertising.amazon.com/API/docs/en-us/dsp-campaigns/#/Image%20Creative/getImageCreatives

**Description of what the documentation currently says**
Says both `name` and `advertiserId` are required

**Description of what the documentation should say**
Either make these fields always present or update the schema to say these fields are optional

**Comment by elizafarley** [comment]
Hi @davidmoss, DSP image creatives should always have an associated `name` and `advertiserId`. It sounds like they are present in list operations, but which operation(s) are you not seeing these fields present in?

**Comment by elizafarley** [comment]
@davidmoss Thanks for providing these examples! This looks like it could be a technical bug, rather than a documentation issue. Could you open a [JIRA ticket](https://amzn-clicks.atlassian.net/servicedesk/customer/portal/2/group/2/create/6) for this issue? Please provide your `clientId` and `requestId` in that ticket so the engineering team can investigate.

**Comment by elizafarley** [comment]
@davidmoss Were you able to resolve this issue through JIRA? Going to close for now, but please reopen if needed.
